{% set name = "phate" %}
{% set version = "0.2.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2c2677e4cff206f5653bba1d003902cf1a0a800c53df9fb3b63a91a080826d3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - future
    - pyqt >=5.6.0
    - graphtools >=0.1.10
    - matplotlib >=2.0.1
    - numpy >=1.14.0
    - pandas >=0.21.0
    - python
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - tasklogger >=0.2

test:
  imports:
    - phate

about:
  home: https://github.com/KrishnaswamyLab/PHATE
  license: GPL-2.0
  license_family: GPL
  summary: PHATE (Potential of Heat-diffusion for Affinity-based Transition Embedding) is a tool for visualizing high dimensional single cell data with natural progressions or trajectories. 
