package:
  name: tpp
  version: "5.5.0"

source:
  fn: TPP_5.0.0-src.tgz
  url: http://downloads.sourceforge.net/project/sashimi/Trans-Proteomic%20Pipeline%20%28TPP%29/TPP%20v5.0%20%28Typhoon%29%20rev%200/TPP_5.0.0-src.tgz
  sha256: caed7a664be42fb9a168df699204816672e640569179cddaa42cf178d339534e

build:
  detect_binary_files_with_prefix: true
  number: 0
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

requirements:
  build:
    - boost {{CONDA_BOOST}}*
    - libgd
    - gcc  # [linux]
    - llvm  # [osx]
    - perl-threaded
    - bzip2
    - zlib
    - libpng
    - libgd
    - gnu-wget
  run:
    - boost {{CONDA_BOOST}}*
    - libgd
    - libgcc  # [linux]
    - perl-threaded
    - bzip2
    - zlib
    - gnuplot
    - libpng
    - libgd

test:
  commands:
    - ProteinProphet -h

about:
  home: http://tools.proteomecenter.org/wiki/index.php?title=Software:TPP
  license: GPL v. 2.0 and LGPL
  summary: The Trans-Proteomic Pipeline (TPP) is an open-source data analysis software for proteomics developed at the Institute for Systems Biology (ISB) by the Ruedi Aebersold group under the Seattle Proteome Center. The TPP includes PeptideProphet,[2] ProteinProphet,[3] ASAPRatio, XPRESS and Libra.
