{% set name = "magic-impute" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b420f3bc7b778365c1b1b0929a389cc4f8fe796e49a32f3bc55f33b6d549113

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - graphtools >=0.1.9
    - matplotlib
    - numpy >=1.14.0
    - pandas >=0.21.0
    - python
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - scprep >=0.7.1
    - tasklogger >=0.2.1

test:
  imports:
    - magic

about:
  home: https://github.com/KrishnaswamyLab/MAGIC
  license: GNU General Public Version 2
  license_family: GPL2
  summary: MAGIC (Markov Affinity-based Graph Imputation of Cells), is a method for imputing missing values restoring structure of large biological datasets. 
