{% set name = "enasearch" %}
{% set version = "0.0.3" %}
{% set md5 = "07dc31cd1aabcfc5496201cb58537735" %}
package:
  name: {{ name }}
  version: {{ version }}
source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/6e/7c/0f5f7757afeb71b0c04fcec717512bb8dc7c0ff8dbb66f469cdfeff7b7dc/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}
build:
  entry_points:
    - enasearch = enasearch.__main__:main
  number: 0
  skip: True # [py3k]
requirements:
  build:
    - python
    - setuptools
    - requests
    - click
    - flake8
    - xmltodict
    - biopython
    - pytest
    - pytest-runner
  run:
    - python
    - requests
    - click
    - flake8
    - xmltodict
    - biopython
test:
  imports:
    - enasearch
    - enasearch_data
  commands:
    - enasearch --help
  requires:
    - pytest
about:
  home: https://github.com/bebatut/enasearch
  license: MIT License
  summary: "A Python library for interacting with ENA's API"
  license_family: MIT

